AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  UpdateWaterGoalTotal:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::005865507601:role/service-role/UpdateWaterGoalTotal-role-c3v4pwqe
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /user/update-water-goal
            Method: PUT
