AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GetWaterDrunkByUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::005865507601:role/service-role/GetWaterDrunkByUser-role-kqx82o37
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /user
            Method: GET
